name: 'Release Notifier'

inputs:
  os-name:
    description: 'OS name (e.g. Linux, Android)'
    required: true
  version:
    description: 'Semantic version string for this release (e.g. 4.0.0-alpha.0)'
    required: true
  status:
    description: 'Final status of the release job (available values: success, failure, cancelled)'
    required: true
  slack_oauth_token:
    description: 'OAuth token for our Slack bot'
    required: true

runs:
  using: composite
  steps:
    - name: 'Success Notification'
      uses: actions-ecosystem/action-slack-notifier@v1
      if: ${{ inputs.status == 'success' }}
      with:
        slack_token: ${{ inputs.slack_oauth_token }}
        username: Github Actions
        color: green
        verbose: true
        message: |
          Release Success - `${{ inputs.os-name }} ${{ inputs.version }}`
        channel: releases
        
    - name: 'Failure Notification'
      uses: actions-ecosystem/action-slack-notifier@v1
      if: ${{ inputs.status == 'failure' }}
      with:
        slack_token: ${{ inputs.slack_oauth_token }}
        username: Github Actions
        color: red
        verbose: true
        message: |
          Release Failed - `${{ inputs.os-name }} ${{ inputs.version }}`
        channel: releases

    - name: 'Cancelled Notification'
      uses: actions-ecosystem/action-slack-notifier@v1
      if: ${{ inputs.status == 'cancelled' }}
      with:
        slack_token: ${{ inputs.slack_oauth_token }}
        username: Github Actions
        color: yellow
        verbose: true
        message: |
          Release Cancelled - `${{ inputs.os-name }} ${{ inputs.version }}`
        channel: releases