name: Mobile Deploy Common

on:
  release:
    types:
      [released, prereleased]

jobs:
  release-start-notification-mobile:
    runs-on: ubuntu-22.04
    if: |
      startsWith(github.ref, 'refs/tags/@quiet/mobile')
      
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: 'recursive'
          
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@fdb5b74adc1278ddb777dfed4c988b9d098bb48d # v1.2.1
        with:
          path: packages/desktop
          
      - name: Send Release Notificaton
        uses: ./.github/actions/release-notifier
        if: always()
        with:
          os-name: Mobile
          version: ${{ steps.extract_version.outputs.version }}
          status: started
          slack_oauth_token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}